name: check

on:
  push:

jobs:
  build:
    name: Build and Scan Docker Image
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enable Docker Content Trust and Build Docker Image
        run: |
          export DOCKER_CONTENT_TRUST=1
          docker build -t built-image:scan .

      - name: Install Dockle
        run: |
          curl -sSfL https://github.com/goodwithtech/dockle/releases/latest/download/dockle_$(uname -s)_$(uname -m).tar.gz | tar zxv
          sudo mv dockle /usr/local/bin/

      - name: Run Dockle Manually
        run: |
          dockle \
            --exit-level warn \
            --exit-code 1 \
            --format list \
            --accept-key NODE_VERSION \
            --accept-key YARN_VERSION \
            --accept-key OPENSSL_ARCH \
            --accept-key GNUPGHOME \
            built-image:scan
