name: check

on:
  push:

jobs:
  build:
    name: Build and Scan Docker Image
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enable Docker Content Trust and Build Docker Image
        run: |
          export DOCKER_CONTENT_TRUST=1
          docker build -t built-image:scan .

      - name: Install Dockle
        run: |
          VERSION=$(curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | \
            grep '"tag_name":' | \
            sed -E 's/.*"v([^"]+)".*/\1/')
          curl -L -o dockle.deb https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.deb
          sudo dpkg -i dockle.deb
          rm dockle.deb

      - name: Run Dockle Manually
        run: |
          dockle \
          --exit-code 1 \
          --ignore CIS-DI-0001 \
          --accept-key NODE_VERSION \
          --accept-key YARN_VERSION \
          --accept-key OPENSSL_ARCH \
          --accept-key GNUPGHOME \
          built-image:scan

