name: check

on:
  push:

jobs:
  build:
    name: Build and Scan Docker Image
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enable Docker Content Trust and Build Image
        run: |
          export DOCKER_CONTENT_TRUST=1
          docker build -t built-image:scan .

      - name: Run Dockle Scan
        uses: goodwithtech/dockle-action@v0.4.15
        with:
          image: 'built-image:scan'
          format: 'list'
          exit-code: '1'
          exit-level: 'warn'
          ignore: 'CIS-DI-0001,DKL-DI-0006'
          accept-key: |
            NODE_VERSION
            YARN_VERSION
            OPENSSL_ARCH
            GNUPGHOME
